// Seed data imported from Notion exports
// This data is inserted on first admin login via /api/seed

export const seedProjects = [
  { name: 'The Hoss', status: 'in_progress' as const, description: 'Primary residence at 21 Harrison Street' },
  { name: 'HSCI', status: 'in_progress' as const, description: 'HSC I LLC business operations' },
  { name: 'The Darby', status: 'in_progress' as const, description: 'The Darby Social Club' },
  { name: '21 Harrison Management', status: 'not_started' as const, description: 'Rental property management — 21 Harrison Street (3 apartments)' },
  { name: '24 Central', status: 'done' as const, description: 'Rental property — 24 Central Street (2 apartments)' },
  { name: 'Kids School', status: 'in_progress' as const, description: 'School-related tasks and information' },
  { name: 'Kids Health', status: 'in_progress' as const, description: 'Kids health appointments and records' },
  { name: 'Budget', status: 'in_progress' as const, description: 'Family budget and financial planning' },
  { name: 'Summer 2026', status: 'in_progress' as const, description: 'Summer 2026 planning' },
  { name: 'Live in Part Time Nanny', status: 'in_progress' as const, description: 'Nanny search and management' },
  { name: 'Aaron Personal', status: 'not_started' as const, description: 'Aaron\'s personal tasks and goals' },
  { name: 'Exercise', status: 'not_started' as const, description: 'Fitness and exercise tracking' },
  { name: 'Year end closeout', status: 'not_started' as const, description: 'End of year financial closeout' },
  { name: 'Health Care For All (HCFA)', status: 'in_progress' as const, description: 'HCFA board involvement' },
  { name: 'Final 21 Harrison Move Out', status: 'done' as const, description: 'Move-out process for 21 Harrison' },
  { name: 'Christmas 2025', status: 'done' as const, description: 'Christmas 2025 planning' },
]

export const seedTasks = [
  // Active / Not started tasks
  { title: 'Winston Passport', project: 'Aaron Personal', person: 'Aaron', status: 'not_started' as const, due_date: '2025-08-30' },
  { title: 'Call Medford dentist re Winston insurance', project: 'Kids Health', person: 'Aaron', status: 'in_progress' as const },
  { title: 'Central Street Stuff', project: 'The Hoss', person: 'Aaron, Michaela', status: 'in_progress' as const },
  { title: 'Rental Property Expenses General Ledger', project: 'HSCI', person: 'Aaron, Michaela', status: 'in_progress' as const },
  { title: 'Hoss supplies', project: 'The Hoss', person: null, status: 'not_started' as const },
  { title: 'Setup SEP IRA for HSCI', project: 'HSCI', person: 'Aaron', status: 'not_started' as const, due_date: '2025-11-15' },
  { title: 'Change ADP to annual account', project: 'HSCI', person: 'Aaron', status: 'not_started' as const },
  { title: '2nd floor bathroom', project: 'The Hoss', person: null, status: 'not_started' as const },
  { title: 'Unit 1', project: 'The Hoss', person: null, status: 'not_started' as const },
  { title: 'Get zero fee corporate card', project: 'HSCI', person: null, status: 'not_started' as const },
  { title: 'Monthly Check List', project: 'HSCI', person: null, status: 'not_started' as const },
  { title: 'Weather strip north patio door', project: 'The Hoss', person: null, status: 'not_started' as const },
  { title: 'Install new modem and cancel modem with Astound', project: 'The Hoss', person: null, status: 'not_started' as const, due_date: '2025-11-28' },
  { title: 'Laundry Room Reno', project: 'The Hoss', person: null, status: 'not_started' as const },
  { title: 'Clean/dirty laundry basket labels', project: 'The Hoss', person: null, status: 'not_started' as const },
  { title: 'Refrigerator', project: 'The Darby', person: null, status: 'not_started' as const },
  { title: 'Cold spots', project: 'The Darby', person: null, status: 'not_started' as const },
  { title: 'Mount exterior security cameras', project: 'The Hoss', person: null, status: 'not_started' as const },
  { title: 'Cold spots in kitchen and trim', project: 'The Hoss', person: null, status: 'not_started' as const },
  { title: 'Basement apartment reno', project: 'The Hoss', person: null, status: 'in_progress' as const },
  { title: 'Lodgism', project: 'The Darby', person: null, status: 'not_started' as const },
  { title: 'MLK Day To Dos', project: 'Aaron Personal', person: 'Aaron', status: 'not_started' as const },
  { title: 'MassSave Energy Audit', project: 'The Hoss', person: null, status: 'not_started' as const },
  { title: 'Cold spots', project: 'The Hoss', person: null, status: 'not_started' as const },
  { title: 'HVAC', project: 'The Hoss', person: null, status: 'not_started' as const },
  { title: 'Transfer utilities', project: 'Final 21 Harrison Move Out', person: 'Aaron', status: 'not_started' as const, due_date: '2025-10-17' },
  // Done tasks (for historical record)
  { title: 'Prius oil change', project: null, person: 'Michaela', status: 'done' as const, due_date: '2025-07-12' },
  { title: 'Camie Dentist', project: null, person: 'Michaela', status: 'done' as const, due_date: '2025-07-09' },
  { title: 'Winston Dentist', project: null, person: 'Michaela', status: 'done' as const, due_date: '2025-07-15' },
  { title: 'Move $ BoA→ Merrill', project: null, person: 'Michaela', status: 'done' as const, due_date: '2025-07-11' },
  { title: 'Change Darby paymt to 1750', project: null, person: 'Michaela', status: 'done' as const, due_date: '2025-07-08' },
  { title: 'Decide after school for 25-26', project: null, person: 'Michaela', status: 'done' as const, due_date: '2025-07-10' },
  { title: 'Darby Dumpster', project: null, person: 'Aaron', status: 'done' as const },
  { title: 'Buy new washer', project: null, person: null, status: 'done' as const },
  { title: 'Drop St Teresa clothes', project: null, person: null, status: 'done' as const },
  { title: 'Tesla service items', project: null, person: null, status: 'done' as const },
  { title: 'Fix outlet in washer/dryer room', project: 'Final 21 Harrison Move Out', person: 'Aaron', status: 'done' as const, due_date: '2025-09-13' },
  { title: 'Add block party people', project: null, person: 'Aaron', status: 'done' as const },
  { title: 'Darby Oil Spill', project: 'The Darby', person: 'Aaron', status: 'done' as const },
  { title: 'Follow up with Yale for fridge replacement piece', project: 'Final 21 Harrison Move Out', person: 'Aaron', status: 'done' as const },
  { title: 'House to dos', project: 'Final 21 Harrison Move Out', person: null, status: 'done' as const },
  { title: 'Records', project: null, person: 'Aaron', status: 'done' as const, due_date: '2025-10-11' },
  { title: 'Meals for week', project: null, person: 'Aaron', status: 'done' as const },
  { title: 'Sunday Morning', project: 'Final 21 Harrison Move Out', person: null, status: 'done' as const },
  { title: 'WiFi solution for basement in November', project: 'Final 21 Harrison Move Out', person: 'Aaron', status: 'done' as const, due_date: '2025-10-18' },
  { title: '2 more smoke alarms', project: 'Final 21 Harrison Move Out', person: 'Aaron', status: 'done' as const, due_date: '2025-10-18' },
  { title: 'Expense Dehumidifier', project: 'The Hoss', person: null, status: 'done' as const },
  { title: 'Chimneys', project: 'The Hoss', person: null, status: 'done' as const },
  { title: 'Aaron\'s office', project: 'The Hoss', person: null, status: 'done' as const },
  { title: 'MyPennyMac - Finish Configuring AutoPay', project: 'The Hoss', person: 'Aaron', status: 'done' as const, due_date: '2025-12-01' },
  { title: 'Home insurance', project: 'The Hoss', person: 'Aaron', status: 'done' as const },
  { title: 'Fireplaces', project: 'The Hoss', person: null, status: 'done' as const },
  { title: 'Rug for east hallway outside unit 1', project: 'The Hoss', person: null, status: 'done' as const },
]

export const seedDocuments = [
  { name: 'Merrill Account Transfer Process', tags: ['Finance'] },
  { name: '2025 Summer', tags: ['Summer'] },
  { name: 'Spring Street Worksheet', tags: ['Real Estate'] },
  { name: 'Exercise', tags: ['Aaron'] },
  { name: 'PCG Separation', tags: ['Aaron'] },
  { name: 'Basement AirBnB', tags: [] },
  { name: '19 Summit Ave', tags: ['Real Estate'] },
  { name: 'HSCI Enterprise Layout', tags: [] },
  { name: 'Travel info', tags: [] },
  { name: 'John F. Kennedy School Information', tags: [], project: 'Kids School' },
  { name: '65 Berkely Street Somerville', tags: ['Real Estate'] },
  { name: 'Neighborhood list', tags: [] },
  { name: 'Darby App (Dappy)', tags: [] },
  { name: 'Central street walkthrough', tags: [] },
  { name: 'HSCI, LLC', tags: [] },
  { name: 'Dead bolts', tags: [], project: 'The Hoss' },
  { name: 'Paint Colors', tags: [], project: 'The Hoss' },
  { name: 'Breakers', tags: [] },
  { name: 'Lauro', tags: [], project: 'The Hoss' },
  { name: 'IPTV', tags: [], project: 'The Hoss' },
  { name: '2025 Taxes', tags: [], project: 'HSCI' },
  { name: 'Camilla\'s class contact info', tags: ['Camie'], project: 'Kids School' },
]

export const seedRecommendations = [
  { name: 'Blood of Zeus', type: 'show' as const, description: 'Not for Michaela', origin: 'Mat Welch' },
  { name: 'HBO The Last of Us Season 2', type: 'show' as const, origin: null },
  { name: 'HBO House of Dragons Season 3', type: 'show' as const, origin: null },
  { name: 'HBO True Detective Night Country', type: 'show' as const, origin: null },
  { name: 'The Alabama Solution', type: 'show' as const, description: 'Documentary on HBO Max about prison system (Michaela will not like)', origin: 'Sean' },
  { name: 'Babe (#1)', type: 'movie' as const, origin: null },
  { name: 'Smash, Boom, Best', type: 'podcast' as const, description: 'Kids podcast', origin: null },
  { name: 'Terrestrials', type: 'podcast' as const, description: 'Radio lab for kids', origin: 'Camden Coalition' },
  { name: 'One Battle After Another', type: 'movie' as const, origin: 'Barack Obama' },
  { name: 'Sinners', type: 'movie' as const, origin: null },
]

export const seedRecipes = [
  { name: 'Lotta Burrata', tags: [] },
  { name: 'Homemade pretzels', tags: [] },
  { name: 'Focaccia', tags: [] },
  { name: 'Nana\'s apple pie', tags: [] },
  { name: 'Guava shrimp', tags: [] },
  { name: 'Pizza crusts', tags: [] },
  { name: 'Agar Cup', tags: [] },
  { name: 'Vegetable Lo Mein for Two', url: 'https://www.forkinthekitchen.com/vegetable-lo-mein-for-two/', tags: ['Dinner'] },
]
